import { DefaultApi } from "./api";

// tslint:disable
/**
 * City Info
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

const api = new DefaultApi();
(async () => {
  await api.addCity({ name: "Eisenstadt", population: 234, size: 123.21 });
  await api.deleteCity("Linz");

  console.log("current cities");
  console.log(await api.listCities());
})();
