import { DefaultApi } from "./api";

// tslint:disable
/**
 * Hello World App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

new DefaultApi()
  .listCities()
  .then(cities => cities.map(city => console.log(`${city.id}: ${city.name}`)));
