swagger: "2.0"
info:
  version: "0.0.1"
  title: City Info
host: localhost:10010

paths:
  /cities:
    x-swagger-router-controller: city_info
    get:
      operationId: listCities
      responses:
        "200":
          $ref: "#/responses/Cities"
    post:
      operationId: addCity
      parameters:
        - in: body
          name: city
          schema:
            $ref: "#/definitions/City"
      responses:
        "200":
          $ref: "#/responses/Cities"
  /cities/{name}:
    x-swagger-router-controller: city_info
    delete:
      operationId: deleteCity
      parameters:
        - name: name
          in: path
          type: string
          required: true
      responses:
        "200":
          $ref: "#/responses/Cities"

responses:
  Cities:
    description: OK
    schema:
      type: array
      items:
        $ref: "#/definitions/City"

definitions:
  City:
    properties:
      name:
        type: string
      population:
        type: integer
      size:
        type: number
